### ISSUE TITLE
Create relationship between models

### ISSUE THREAD

**Issue by Dirane** [ubcsc/ubcsc-website#10]
Establish relationship(one-to-one, one-to-many, many-to-one, polymorphic relations)  between related models as specified by the .png file bellow.
![ubcsc](https://user-images.githubusercontent.com/16786975/39576818-5a8cf6f8-4ed7-11e8-92d6-6f958943e19a.png)

**Comment by pilalouis** [comment]
so we need to first generate to first of generate 9 models

**Comment by Dirane** [comment]
@Louis95 Yeah sure, before creating relations we need first of all to generate the models.

**Comment by Dirane** [comment]
Solved
